
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Accordion: typeof import("../app/components/ui/accordion/index")['Accordion']
export const AccordionContent: typeof import("../app/components/ui/accordion/index")['AccordionContent']
export const AccordionItem: typeof import("../app/components/ui/accordion/index")['AccordionItem']
export const AccordionTrigger: typeof import("../app/components/ui/accordion/index")['AccordionTrigger']
export const Alert: typeof import("../app/components/ui/alert/index")['Alert']
export const AlertDescription: typeof import("../app/components/ui/alert/index")['AlertDescription']
export const AlertTitle: typeof import("../app/components/ui/alert/index")['AlertTitle']
export const AlertDialog: typeof import("../app/components/ui/alert-dialog/index")['AlertDialog']
export const AlertDialogAction: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogAction']
export const AlertDialogCancel: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogCancel']
export const AlertDialogContent: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogContent']
export const AlertDialogDescription: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogDescription']
export const AlertDialogFooter: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogFooter']
export const AlertDialogHeader: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogHeader']
export const AlertDialogTitle: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTitle']
export const AlertDialogTrigger: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTrigger']
export const AspectRatio: typeof import("../app/components/ui/aspect-ratio/index")['AspectRatio']
export const AutoForm: typeof import("../app/components/ui/auto-form/index")['AutoForm']
export const AutoFormField: typeof import("../app/components/ui/auto-form/index")['AutoFormField']
export const AutoFormFieldArray: typeof import("../app/components/ui/auto-form/index")['AutoFormFieldArray']
export const AutoFormFieldBoolean: typeof import("../app/components/ui/auto-form/index")['AutoFormFieldBoolean']
export const AutoFormFieldDate: typeof import("../app/components/ui/auto-form/index")['AutoFormFieldDate']
export const AutoFormFieldEnum: typeof import("../app/components/ui/auto-form/index")['AutoFormFieldEnum']
export const AutoFormFieldFile: typeof import("../app/components/ui/auto-form/index")['AutoFormFieldFile']
export const AutoFormFieldInput: typeof import("../app/components/ui/auto-form/index")['AutoFormFieldInput']
export const AutoFormFieldNumber: typeof import("../app/components/ui/auto-form/index")['AutoFormFieldNumber']
export const AutoFormFieldObject: typeof import("../app/components/ui/auto-form/index")['AutoFormFieldObject']
export const AutoFormLabel: typeof import("../app/components/ui/auto-form/index")['AutoFormLabel']
export const Config: typeof import("../app/components/ui/auto-form/index")['Config']
export const ConfigItem: typeof import("../app/components/ui/auto-form/index")['ConfigItem']
export const FieldProps: typeof import("../app/components/ui/auto-form/index")['FieldProps']
export const Avatar: typeof import("../app/components/ui/avatar/index")['Avatar']
export const AvatarFallback: typeof import("../app/components/ui/avatar/index")['AvatarFallback']
export const AvatarImage: typeof import("../app/components/ui/avatar/index")['AvatarImage']
export const Badge: typeof import("../app/components/ui/badge/index")['Badge']
export const Button: typeof import("../app/components/ui/button/index")['Button']
export const Calendar: typeof import("../app/components/ui/calendar/index")['Calendar']
export const CalendarCell: typeof import("../app/components/ui/calendar/index")['CalendarCell']
export const CalendarCellTrigger: typeof import("../app/components/ui/calendar/index")['CalendarCellTrigger']
export const CalendarGrid: typeof import("../app/components/ui/calendar/index")['CalendarGrid']
export const CalendarGridBody: typeof import("../app/components/ui/calendar/index")['CalendarGridBody']
export const CalendarGridHead: typeof import("../app/components/ui/calendar/index")['CalendarGridHead']
export const CalendarGridRow: typeof import("../app/components/ui/calendar/index")['CalendarGridRow']
export const CalendarHeadCell: typeof import("../app/components/ui/calendar/index")['CalendarHeadCell']
export const CalendarHeader: typeof import("../app/components/ui/calendar/index")['CalendarHeader']
export const CalendarHeading: typeof import("../app/components/ui/calendar/index")['CalendarHeading']
export const CalendarNextButton: typeof import("../app/components/ui/calendar/index")['CalendarNextButton']
export const CalendarPrevButton: typeof import("../app/components/ui/calendar/index")['CalendarPrevButton']
export const Card: typeof import("../app/components/ui/card/index")['Card']
export const CardAction: typeof import("../app/components/ui/card/index")['CardAction']
export const CardContent: typeof import("../app/components/ui/card/index")['CardContent']
export const CardDescription: typeof import("../app/components/ui/card/index")['CardDescription']
export const CardFooter: typeof import("../app/components/ui/card/index")['CardFooter']
export const CardHeader: typeof import("../app/components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../app/components/ui/card/index")['CardTitle']
export const Checkbox: typeof import("../app/components/ui/checkbox/index")['Checkbox']
export const Dialog: typeof import("../app/components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../app/components/ui/dialog/index")['DialogClose']
export const DialogContent: typeof import("../app/components/ui/dialog/index")['DialogContent']
export const DialogDescription: typeof import("../app/components/ui/dialog/index")['DialogDescription']
export const DialogFooter: typeof import("../app/components/ui/dialog/index")['DialogFooter']
export const DialogHeader: typeof import("../app/components/ui/dialog/index")['DialogHeader']
export const DialogOverlay: typeof import("../app/components/ui/dialog/index")['DialogOverlay']
export const DialogScrollContent: typeof import("../app/components/ui/dialog/index")['DialogScrollContent']
export const DialogTitle: typeof import("../app/components/ui/dialog/index")['DialogTitle']
export const DialogTrigger: typeof import("../app/components/ui/dialog/index")['DialogTrigger']
export const DropdownMenu: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuCheckboxItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuLabel: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuRadioGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuRadioItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuSeparator: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuShortcut: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSub: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const DropdownMenuSubTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuPortal: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const FormControl: typeof import("../app/components/ui/form/index")['FormControl']
export const FormDescription: typeof import("../app/components/ui/form/index")['FormDescription']
export const FormItem: typeof import("../app/components/ui/form/index")['FormItem']
export const FormLabel: typeof import("../app/components/ui/form/index")['FormLabel']
export const FormMessage: typeof import("../app/components/ui/form/index")['FormMessage']
export const FORMITEMINJECTIONKEY: typeof import("../app/components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const Form: typeof import("../app/components/ui/form/index")['Form']
export const FormField: typeof import("../app/components/ui/form/index")['FormField']
export const FormFieldArray: typeof import("../app/components/ui/form/index")['FormFieldArray']
export const Input: typeof import("../app/components/ui/input/index")['Input']
export const Label: typeof import("../app/components/ui/label/index")['Label']
export const Menubar: typeof import("../app/components/ui/menubar/index")['Menubar']
export const MenubarCheckboxItem: typeof import("../app/components/ui/menubar/index")['MenubarCheckboxItem']
export const MenubarContent: typeof import("../app/components/ui/menubar/index")['MenubarContent']
export const MenubarGroup: typeof import("../app/components/ui/menubar/index")['MenubarGroup']
export const MenubarItem: typeof import("../app/components/ui/menubar/index")['MenubarItem']
export const MenubarLabel: typeof import("../app/components/ui/menubar/index")['MenubarLabel']
export const MenubarMenu: typeof import("../app/components/ui/menubar/index")['MenubarMenu']
export const MenubarRadioGroup: typeof import("../app/components/ui/menubar/index")['MenubarRadioGroup']
export const MenubarRadioItem: typeof import("../app/components/ui/menubar/index")['MenubarRadioItem']
export const MenubarSeparator: typeof import("../app/components/ui/menubar/index")['MenubarSeparator']
export const MenubarShortcut: typeof import("../app/components/ui/menubar/index")['MenubarShortcut']
export const MenubarSub: typeof import("../app/components/ui/menubar/index")['MenubarSub']
export const MenubarSubContent: typeof import("../app/components/ui/menubar/index")['MenubarSubContent']
export const MenubarSubTrigger: typeof import("../app/components/ui/menubar/index")['MenubarSubTrigger']
export const MenubarTrigger: typeof import("../app/components/ui/menubar/index")['MenubarTrigger']
export const Pagination: typeof import("../app/components/ui/pagination/index")['Pagination']
export const PaginationContent: typeof import("../app/components/ui/pagination/index")['PaginationContent']
export const PaginationEllipsis: typeof import("../app/components/ui/pagination/index")['PaginationEllipsis']
export const PaginationFirst: typeof import("../app/components/ui/pagination/index")['PaginationFirst']
export const PaginationItem: typeof import("../app/components/ui/pagination/index")['PaginationItem']
export const PaginationLast: typeof import("../app/components/ui/pagination/index")['PaginationLast']
export const PaginationNext: typeof import("../app/components/ui/pagination/index")['PaginationNext']
export const PaginationPrevious: typeof import("../app/components/ui/pagination/index")['PaginationPrevious']
export const Popover: typeof import("../app/components/ui/popover/index")['Popover']
export const PopoverAnchor: typeof import("../app/components/ui/popover/index")['PopoverAnchor']
export const PopoverContent: typeof import("../app/components/ui/popover/index")['PopoverContent']
export const PopoverTrigger: typeof import("../app/components/ui/popover/index")['PopoverTrigger']
export const Progress: typeof import("../app/components/ui/progress/index")['Progress']
export const RadioGroup: typeof import("../app/components/ui/radio-group/index")['RadioGroup']
export const RadioGroupItem: typeof import("../app/components/ui/radio-group/index")['RadioGroupItem']
export const RangeCalendar: typeof import("../app/components/ui/range-calendar/index")['RangeCalendar']
export const RangeCalendarCell: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarCell']
export const RangeCalendarCellTrigger: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarCellTrigger']
export const RangeCalendarGrid: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGrid']
export const RangeCalendarGridBody: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridBody']
export const RangeCalendarGridHead: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridHead']
export const RangeCalendarGridRow: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridRow']
export const RangeCalendarHeadCell: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeadCell']
export const RangeCalendarHeader: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeader']
export const RangeCalendarHeading: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeading']
export const RangeCalendarNextButton: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarNextButton']
export const RangeCalendarPrevButton: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarPrevButton']
export const Select: typeof import("../app/components/ui/select/index")['Select']
export const SelectContent: typeof import("../app/components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../app/components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../app/components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../app/components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../app/components/ui/select/index")['SelectLabel']
export const SelectScrollDownButton: typeof import("../app/components/ui/select/index")['SelectScrollDownButton']
export const SelectScrollUpButton: typeof import("../app/components/ui/select/index")['SelectScrollUpButton']
export const SelectSeparator: typeof import("../app/components/ui/select/index")['SelectSeparator']
export const SelectTrigger: typeof import("../app/components/ui/select/index")['SelectTrigger']
export const SelectValue: typeof import("../app/components/ui/select/index")['SelectValue']
export const Separator: typeof import("../app/components/ui/separator/index")['Separator']
export const Slider: typeof import("../app/components/ui/slider/index")['Slider']
export const Toaster: typeof import("../app/components/ui/sonner/index")['Toaster']
export const Stepper: typeof import("../app/components/ui/stepper/index")['Stepper']
export const StepperDescription: typeof import("../app/components/ui/stepper/index")['StepperDescription']
export const StepperIndicator: typeof import("../app/components/ui/stepper/index")['StepperIndicator']
export const StepperItem: typeof import("../app/components/ui/stepper/index")['StepperItem']
export const StepperSeparator: typeof import("../app/components/ui/stepper/index")['StepperSeparator']
export const StepperTitle: typeof import("../app/components/ui/stepper/index")['StepperTitle']
export const StepperTrigger: typeof import("../app/components/ui/stepper/index")['StepperTrigger']
export const Switch: typeof import("../app/components/ui/switch/index")['Switch']
export const Textarea: typeof import("../app/components/ui/textarea/index")['Textarea']
export const Toggle: typeof import("../app/components/ui/toggle/index")['Toggle']
export const Tooltip: typeof import("../app/components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../app/components/ui/tooltip/index")['TooltipContent']
export const TooltipProvider: typeof import("../app/components/ui/tooltip/index")['TooltipProvider']
export const TooltipTrigger: typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']
export const VitePwaManifest: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@vue+compiler-dom@3.5.33_2dd188fc485186898f356a806aeb85c3/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@vue+compiler-dom@3.5.33_2dd188fc485186898f356a806aeb85c3/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyAccordion: LazyComponent<typeof import("../app/components/ui/accordion/index")['Accordion']>
export const LazyAccordionContent: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionContent']>
export const LazyAccordionItem: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionItem']>
export const LazyAccordionTrigger: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionTrigger']>
export const LazyAlert: LazyComponent<typeof import("../app/components/ui/alert/index")['Alert']>
export const LazyAlertDescription: LazyComponent<typeof import("../app/components/ui/alert/index")['AlertDescription']>
export const LazyAlertTitle: LazyComponent<typeof import("../app/components/ui/alert/index")['AlertTitle']>
export const LazyAlertDialog: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialog']>
export const LazyAlertDialogAction: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogAction']>
export const LazyAlertDialogCancel: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogCancel']>
export const LazyAlertDialogContent: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogContent']>
export const LazyAlertDialogDescription: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogDescription']>
export const LazyAlertDialogFooter: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogFooter']>
export const LazyAlertDialogHeader: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogHeader']>
export const LazyAlertDialogTitle: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTitle']>
export const LazyAlertDialogTrigger: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTrigger']>
export const LazyAspectRatio: LazyComponent<typeof import("../app/components/ui/aspect-ratio/index")['AspectRatio']>
export const LazyAutoForm: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoForm']>
export const LazyAutoFormField: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormField']>
export const LazyAutoFormFieldArray: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormFieldArray']>
export const LazyAutoFormFieldBoolean: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormFieldBoolean']>
export const LazyAutoFormFieldDate: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormFieldDate']>
export const LazyAutoFormFieldEnum: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormFieldEnum']>
export const LazyAutoFormFieldFile: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormFieldFile']>
export const LazyAutoFormFieldInput: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormFieldInput']>
export const LazyAutoFormFieldNumber: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormFieldNumber']>
export const LazyAutoFormFieldObject: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormFieldObject']>
export const LazyAutoFormLabel: LazyComponent<typeof import("../app/components/ui/auto-form/index")['AutoFormLabel']>
export const LazyConfig: LazyComponent<typeof import("../app/components/ui/auto-form/index")['Config']>
export const LazyConfigItem: LazyComponent<typeof import("../app/components/ui/auto-form/index")['ConfigItem']>
export const LazyFieldProps: LazyComponent<typeof import("../app/components/ui/auto-form/index")['FieldProps']>
export const LazyAvatar: LazyComponent<typeof import("../app/components/ui/avatar/index")['Avatar']>
export const LazyAvatarFallback: LazyComponent<typeof import("../app/components/ui/avatar/index")['AvatarFallback']>
export const LazyAvatarImage: LazyComponent<typeof import("../app/components/ui/avatar/index")['AvatarImage']>
export const LazyBadge: LazyComponent<typeof import("../app/components/ui/badge/index")['Badge']>
export const LazyButton: LazyComponent<typeof import("../app/components/ui/button/index")['Button']>
export const LazyCalendar: LazyComponent<typeof import("../app/components/ui/calendar/index")['Calendar']>
export const LazyCalendarCell: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarCell']>
export const LazyCalendarCellTrigger: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarCellTrigger']>
export const LazyCalendarGrid: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGrid']>
export const LazyCalendarGridBody: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGridBody']>
export const LazyCalendarGridHead: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGridHead']>
export const LazyCalendarGridRow: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGridRow']>
export const LazyCalendarHeadCell: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarHeadCell']>
export const LazyCalendarHeader: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarHeader']>
export const LazyCalendarHeading: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarHeading']>
export const LazyCalendarNextButton: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarNextButton']>
export const LazyCalendarPrevButton: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarPrevButton']>
export const LazyCard: LazyComponent<typeof import("../app/components/ui/card/index")['Card']>
export const LazyCardAction: LazyComponent<typeof import("../app/components/ui/card/index")['CardAction']>
export const LazyCardContent: LazyComponent<typeof import("../app/components/ui/card/index")['CardContent']>
export const LazyCardDescription: LazyComponent<typeof import("../app/components/ui/card/index")['CardDescription']>
export const LazyCardFooter: LazyComponent<typeof import("../app/components/ui/card/index")['CardFooter']>
export const LazyCardHeader: LazyComponent<typeof import("../app/components/ui/card/index")['CardHeader']>
export const LazyCardTitle: LazyComponent<typeof import("../app/components/ui/card/index")['CardTitle']>
export const LazyCheckbox: LazyComponent<typeof import("../app/components/ui/checkbox/index")['Checkbox']>
export const LazyDialog: LazyComponent<typeof import("../app/components/ui/dialog/index")['Dialog']>
export const LazyDialogClose: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogClose']>
export const LazyDialogContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogContent']>
export const LazyDialogDescription: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogDescription']>
export const LazyDialogFooter: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogFooter']>
export const LazyDialogHeader: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogHeader']>
export const LazyDialogOverlay: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogOverlay']>
export const LazyDialogScrollContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogScrollContent']>
export const LazyDialogTitle: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTitle']>
export const LazyDialogTrigger: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTrigger']>
export const LazyDropdownMenu: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
export const LazyDropdownMenuPortal: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
export const LazyFormControl: LazyComponent<typeof import("../app/components/ui/form/index")['FormControl']>
export const LazyFormDescription: LazyComponent<typeof import("../app/components/ui/form/index")['FormDescription']>
export const LazyFormItem: LazyComponent<typeof import("../app/components/ui/form/index")['FormItem']>
export const LazyFormLabel: LazyComponent<typeof import("../app/components/ui/form/index")['FormLabel']>
export const LazyFormMessage: LazyComponent<typeof import("../app/components/ui/form/index")['FormMessage']>
export const LazyFORMITEMINJECTIONKEY: LazyComponent<typeof import("../app/components/ui/form/index")['FORM_ITEM_INJECTION_KEY']>
export const LazyForm: LazyComponent<typeof import("../app/components/ui/form/index")['Form']>
export const LazyFormField: LazyComponent<typeof import("../app/components/ui/form/index")['FormField']>
export const LazyFormFieldArray: LazyComponent<typeof import("../app/components/ui/form/index")['FormFieldArray']>
export const LazyInput: LazyComponent<typeof import("../app/components/ui/input/index")['Input']>
export const LazyLabel: LazyComponent<typeof import("../app/components/ui/label/index")['Label']>
export const LazyMenubar: LazyComponent<typeof import("../app/components/ui/menubar/index")['Menubar']>
export const LazyMenubarCheckboxItem: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarCheckboxItem']>
export const LazyMenubarContent: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarContent']>
export const LazyMenubarGroup: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarGroup']>
export const LazyMenubarItem: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarItem']>
export const LazyMenubarLabel: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarLabel']>
export const LazyMenubarMenu: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarMenu']>
export const LazyMenubarRadioGroup: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarRadioGroup']>
export const LazyMenubarRadioItem: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarRadioItem']>
export const LazyMenubarSeparator: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarSeparator']>
export const LazyMenubarShortcut: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarShortcut']>
export const LazyMenubarSub: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarSub']>
export const LazyMenubarSubContent: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarSubContent']>
export const LazyMenubarSubTrigger: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarSubTrigger']>
export const LazyMenubarTrigger: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarTrigger']>
export const LazyPagination: LazyComponent<typeof import("../app/components/ui/pagination/index")['Pagination']>
export const LazyPaginationContent: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationContent']>
export const LazyPaginationEllipsis: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationEllipsis']>
export const LazyPaginationFirst: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationFirst']>
export const LazyPaginationItem: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationItem']>
export const LazyPaginationLast: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationLast']>
export const LazyPaginationNext: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationNext']>
export const LazyPaginationPrevious: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationPrevious']>
export const LazyPopover: LazyComponent<typeof import("../app/components/ui/popover/index")['Popover']>
export const LazyPopoverAnchor: LazyComponent<typeof import("../app/components/ui/popover/index")['PopoverAnchor']>
export const LazyPopoverContent: LazyComponent<typeof import("../app/components/ui/popover/index")['PopoverContent']>
export const LazyPopoverTrigger: LazyComponent<typeof import("../app/components/ui/popover/index")['PopoverTrigger']>
export const LazyProgress: LazyComponent<typeof import("../app/components/ui/progress/index")['Progress']>
export const LazyRadioGroup: LazyComponent<typeof import("../app/components/ui/radio-group/index")['RadioGroup']>
export const LazyRadioGroupItem: LazyComponent<typeof import("../app/components/ui/radio-group/index")['RadioGroupItem']>
export const LazyRangeCalendar: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendar']>
export const LazyRangeCalendarCell: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarCell']>
export const LazyRangeCalendarCellTrigger: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarCellTrigger']>
export const LazyRangeCalendarGrid: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGrid']>
export const LazyRangeCalendarGridBody: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridBody']>
export const LazyRangeCalendarGridHead: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridHead']>
export const LazyRangeCalendarGridRow: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridRow']>
export const LazyRangeCalendarHeadCell: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeadCell']>
export const LazyRangeCalendarHeader: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeader']>
export const LazyRangeCalendarHeading: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeading']>
export const LazyRangeCalendarNextButton: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarNextButton']>
export const LazyRangeCalendarPrevButton: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarPrevButton']>
export const LazySelect: LazyComponent<typeof import("../app/components/ui/select/index")['Select']>
export const LazySelectContent: LazyComponent<typeof import("../app/components/ui/select/index")['SelectContent']>
export const LazySelectGroup: LazyComponent<typeof import("../app/components/ui/select/index")['SelectGroup']>
export const LazySelectItem: LazyComponent<typeof import("../app/components/ui/select/index")['SelectItem']>
export const LazySelectItemText: LazyComponent<typeof import("../app/components/ui/select/index")['SelectItemText']>
export const LazySelectLabel: LazyComponent<typeof import("../app/components/ui/select/index")['SelectLabel']>
export const LazySelectScrollDownButton: LazyComponent<typeof import("../app/components/ui/select/index")['SelectScrollDownButton']>
export const LazySelectScrollUpButton: LazyComponent<typeof import("../app/components/ui/select/index")['SelectScrollUpButton']>
export const LazySelectSeparator: LazyComponent<typeof import("../app/components/ui/select/index")['SelectSeparator']>
export const LazySelectTrigger: LazyComponent<typeof import("../app/components/ui/select/index")['SelectTrigger']>
export const LazySelectValue: LazyComponent<typeof import("../app/components/ui/select/index")['SelectValue']>
export const LazySeparator: LazyComponent<typeof import("../app/components/ui/separator/index")['Separator']>
export const LazySlider: LazyComponent<typeof import("../app/components/ui/slider/index")['Slider']>
export const LazyToaster: LazyComponent<typeof import("../app/components/ui/sonner/index")['Toaster']>
export const LazyStepper: LazyComponent<typeof import("../app/components/ui/stepper/index")['Stepper']>
export const LazyStepperDescription: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperDescription']>
export const LazyStepperIndicator: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperIndicator']>
export const LazyStepperItem: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperItem']>
export const LazyStepperSeparator: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperSeparator']>
export const LazyStepperTitle: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperTitle']>
export const LazyStepperTrigger: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperTrigger']>
export const LazySwitch: LazyComponent<typeof import("../app/components/ui/switch/index")['Switch']>
export const LazyTextarea: LazyComponent<typeof import("../app/components/ui/textarea/index")['Textarea']>
export const LazyToggle: LazyComponent<typeof import("../app/components/ui/toggle/index")['Toggle']>
export const LazyTooltip: LazyComponent<typeof import("../app/components/ui/tooltip/index")['Tooltip']>
export const LazyTooltipContent: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipContent']>
export const LazyTooltipProvider: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipProvider']>
export const LazyTooltipTrigger: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']>
export const LazyVitePwaManifest: LazyComponent<typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaManifest: LazyComponent<typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaAssets: LazyComponent<typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
export const LazyPwaAppleImage: LazyComponent<typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']>
export const LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']>
export const LazyPwaFaviconImage: LazyComponent<typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']>
export const LazyPwaMaskableImage: LazyComponent<typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']>
export const LazyPwaTransparentImage: LazyComponent<typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@vue+compiler-dom@3.5.33_2dd188fc485186898f356a806aeb85c3/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@vue+compiler-dom@3.5.33_2dd188fc485186898f356a806aeb85c3/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
