
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  NuxtWelcome: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  Accordion: typeof import("../../app/components/ui/accordion/index")['Accordion']
  AccordionContent: typeof import("../../app/components/ui/accordion/index")['AccordionContent']
  AccordionItem: typeof import("../../app/components/ui/accordion/index")['AccordionItem']
  AccordionTrigger: typeof import("../../app/components/ui/accordion/index")['AccordionTrigger']
  Alert: typeof import("../../app/components/ui/alert/index")['Alert']
  AlertDescription: typeof import("../../app/components/ui/alert/index")['AlertDescription']
  AlertTitle: typeof import("../../app/components/ui/alert/index")['AlertTitle']
  AlertDialog: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']
  AlertDialogAction: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']
  AlertDialogCancel: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']
  AlertDialogContent: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']
  AlertDialogDescription: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']
  AlertDialogFooter: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']
  AlertDialogHeader: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']
  AlertDialogTitle: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']
  AlertDialogTrigger: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']
  AspectRatio: typeof import("../../app/components/ui/aspect-ratio/index")['AspectRatio']
  AutoForm: typeof import("../../app/components/ui/auto-form/index")['AutoForm']
  AutoFormField: typeof import("../../app/components/ui/auto-form/index")['AutoFormField']
  AutoFormFieldArray: typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldArray']
  AutoFormFieldBoolean: typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldBoolean']
  AutoFormFieldDate: typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldDate']
  AutoFormFieldEnum: typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldEnum']
  AutoFormFieldFile: typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldFile']
  AutoFormFieldInput: typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldInput']
  AutoFormFieldNumber: typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldNumber']
  AutoFormFieldObject: typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldObject']
  AutoFormLabel: typeof import("../../app/components/ui/auto-form/index")['AutoFormLabel']
  Config: typeof import("../../app/components/ui/auto-form/index")['Config']
  ConfigItem: typeof import("../../app/components/ui/auto-form/index")['ConfigItem']
  FieldProps: typeof import("../../app/components/ui/auto-form/index")['FieldProps']
  Avatar: typeof import("../../app/components/ui/avatar/index")['Avatar']
  AvatarFallback: typeof import("../../app/components/ui/avatar/index")['AvatarFallback']
  AvatarImage: typeof import("../../app/components/ui/avatar/index")['AvatarImage']
  Badge: typeof import("../../app/components/ui/badge/index")['Badge']
  Button: typeof import("../../app/components/ui/button/index")['Button']
  Calendar: typeof import("../../app/components/ui/calendar/index")['Calendar']
  CalendarCell: typeof import("../../app/components/ui/calendar/index")['CalendarCell']
  CalendarCellTrigger: typeof import("../../app/components/ui/calendar/index")['CalendarCellTrigger']
  CalendarGrid: typeof import("../../app/components/ui/calendar/index")['CalendarGrid']
  CalendarGridBody: typeof import("../../app/components/ui/calendar/index")['CalendarGridBody']
  CalendarGridHead: typeof import("../../app/components/ui/calendar/index")['CalendarGridHead']
  CalendarGridRow: typeof import("../../app/components/ui/calendar/index")['CalendarGridRow']
  CalendarHeadCell: typeof import("../../app/components/ui/calendar/index")['CalendarHeadCell']
  CalendarHeader: typeof import("../../app/components/ui/calendar/index")['CalendarHeader']
  CalendarHeading: typeof import("../../app/components/ui/calendar/index")['CalendarHeading']
  CalendarNextButton: typeof import("../../app/components/ui/calendar/index")['CalendarNextButton']
  CalendarPrevButton: typeof import("../../app/components/ui/calendar/index")['CalendarPrevButton']
  Card: typeof import("../../app/components/ui/card/index")['Card']
  CardAction: typeof import("../../app/components/ui/card/index")['CardAction']
  CardContent: typeof import("../../app/components/ui/card/index")['CardContent']
  CardDescription: typeof import("../../app/components/ui/card/index")['CardDescription']
  CardFooter: typeof import("../../app/components/ui/card/index")['CardFooter']
  CardHeader: typeof import("../../app/components/ui/card/index")['CardHeader']
  CardTitle: typeof import("../../app/components/ui/card/index")['CardTitle']
  Checkbox: typeof import("../../app/components/ui/checkbox/index")['Checkbox']
  Dialog: typeof import("../../app/components/ui/dialog/index")['Dialog']
  DialogClose: typeof import("../../app/components/ui/dialog/index")['DialogClose']
  DialogContent: typeof import("../../app/components/ui/dialog/index")['DialogContent']
  DialogDescription: typeof import("../../app/components/ui/dialog/index")['DialogDescription']
  DialogFooter: typeof import("../../app/components/ui/dialog/index")['DialogFooter']
  DialogHeader: typeof import("../../app/components/ui/dialog/index")['DialogHeader']
  DialogOverlay: typeof import("../../app/components/ui/dialog/index")['DialogOverlay']
  DialogScrollContent: typeof import("../../app/components/ui/dialog/index")['DialogScrollContent']
  DialogTitle: typeof import("../../app/components/ui/dialog/index")['DialogTitle']
  DialogTrigger: typeof import("../../app/components/ui/dialog/index")['DialogTrigger']
  DropdownMenu: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']
  DropdownMenuCheckboxItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
  DropdownMenuContent: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
  DropdownMenuGroup: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
  DropdownMenuItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
  DropdownMenuLabel: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
  DropdownMenuRadioGroup: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
  DropdownMenuRadioItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
  DropdownMenuSeparator: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
  DropdownMenuShortcut: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
  DropdownMenuSub: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
  DropdownMenuSubContent: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
  DropdownMenuSubTrigger: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
  DropdownMenuTrigger: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
  DropdownMenuPortal: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
  FormControl: typeof import("../../app/components/ui/form/index")['FormControl']
  FormDescription: typeof import("../../app/components/ui/form/index")['FormDescription']
  FormItem: typeof import("../../app/components/ui/form/index")['FormItem']
  FormLabel: typeof import("../../app/components/ui/form/index")['FormLabel']
  FormMessage: typeof import("../../app/components/ui/form/index")['FormMessage']
  FORMITEMINJECTIONKEY: typeof import("../../app/components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
  Form: typeof import("../../app/components/ui/form/index")['Form']
  FormField: typeof import("../../app/components/ui/form/index")['FormField']
  FormFieldArray: typeof import("../../app/components/ui/form/index")['FormFieldArray']
  Input: typeof import("../../app/components/ui/input/index")['Input']
  Label: typeof import("../../app/components/ui/label/index")['Label']
  Menubar: typeof import("../../app/components/ui/menubar/index")['Menubar']
  MenubarCheckboxItem: typeof import("../../app/components/ui/menubar/index")['MenubarCheckboxItem']
  MenubarContent: typeof import("../../app/components/ui/menubar/index")['MenubarContent']
  MenubarGroup: typeof import("../../app/components/ui/menubar/index")['MenubarGroup']
  MenubarItem: typeof import("../../app/components/ui/menubar/index")['MenubarItem']
  MenubarLabel: typeof import("../../app/components/ui/menubar/index")['MenubarLabel']
  MenubarMenu: typeof import("../../app/components/ui/menubar/index")['MenubarMenu']
  MenubarRadioGroup: typeof import("../../app/components/ui/menubar/index")['MenubarRadioGroup']
  MenubarRadioItem: typeof import("../../app/components/ui/menubar/index")['MenubarRadioItem']
  MenubarSeparator: typeof import("../../app/components/ui/menubar/index")['MenubarSeparator']
  MenubarShortcut: typeof import("../../app/components/ui/menubar/index")['MenubarShortcut']
  MenubarSub: typeof import("../../app/components/ui/menubar/index")['MenubarSub']
  MenubarSubContent: typeof import("../../app/components/ui/menubar/index")['MenubarSubContent']
  MenubarSubTrigger: typeof import("../../app/components/ui/menubar/index")['MenubarSubTrigger']
  MenubarTrigger: typeof import("../../app/components/ui/menubar/index")['MenubarTrigger']
  Pagination: typeof import("../../app/components/ui/pagination/index")['Pagination']
  PaginationContent: typeof import("../../app/components/ui/pagination/index")['PaginationContent']
  PaginationEllipsis: typeof import("../../app/components/ui/pagination/index")['PaginationEllipsis']
  PaginationFirst: typeof import("../../app/components/ui/pagination/index")['PaginationFirst']
  PaginationItem: typeof import("../../app/components/ui/pagination/index")['PaginationItem']
  PaginationLast: typeof import("../../app/components/ui/pagination/index")['PaginationLast']
  PaginationNext: typeof import("../../app/components/ui/pagination/index")['PaginationNext']
  PaginationPrevious: typeof import("../../app/components/ui/pagination/index")['PaginationPrevious']
  Popover: typeof import("../../app/components/ui/popover/index")['Popover']
  PopoverAnchor: typeof import("../../app/components/ui/popover/index")['PopoverAnchor']
  PopoverContent: typeof import("../../app/components/ui/popover/index")['PopoverContent']
  PopoverTrigger: typeof import("../../app/components/ui/popover/index")['PopoverTrigger']
  Progress: typeof import("../../app/components/ui/progress/index")['Progress']
  RadioGroup: typeof import("../../app/components/ui/radio-group/index")['RadioGroup']
  RadioGroupItem: typeof import("../../app/components/ui/radio-group/index")['RadioGroupItem']
  RangeCalendar: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendar']
  RangeCalendarCell: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarCell']
  RangeCalendarCellTrigger: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarCellTrigger']
  RangeCalendarGrid: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGrid']
  RangeCalendarGridBody: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridBody']
  RangeCalendarGridHead: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridHead']
  RangeCalendarGridRow: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridRow']
  RangeCalendarHeadCell: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeadCell']
  RangeCalendarHeader: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeader']
  RangeCalendarHeading: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeading']
  RangeCalendarNextButton: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarNextButton']
  RangeCalendarPrevButton: typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarPrevButton']
  Select: typeof import("../../app/components/ui/select/index")['Select']
  SelectContent: typeof import("../../app/components/ui/select/index")['SelectContent']
  SelectGroup: typeof import("../../app/components/ui/select/index")['SelectGroup']
  SelectItem: typeof import("../../app/components/ui/select/index")['SelectItem']
  SelectItemText: typeof import("../../app/components/ui/select/index")['SelectItemText']
  SelectLabel: typeof import("../../app/components/ui/select/index")['SelectLabel']
  SelectScrollDownButton: typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']
  SelectScrollUpButton: typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']
  SelectSeparator: typeof import("../../app/components/ui/select/index")['SelectSeparator']
  SelectTrigger: typeof import("../../app/components/ui/select/index")['SelectTrigger']
  SelectValue: typeof import("../../app/components/ui/select/index")['SelectValue']
  Separator: typeof import("../../app/components/ui/separator/index")['Separator']
  Slider: typeof import("../../app/components/ui/slider/index")['Slider']
  Toaster: typeof import("../../app/components/ui/sonner/index")['Toaster']
  Stepper: typeof import("../../app/components/ui/stepper/index")['Stepper']
  StepperDescription: typeof import("../../app/components/ui/stepper/index")['StepperDescription']
  StepperIndicator: typeof import("../../app/components/ui/stepper/index")['StepperIndicator']
  StepperItem: typeof import("../../app/components/ui/stepper/index")['StepperItem']
  StepperSeparator: typeof import("../../app/components/ui/stepper/index")['StepperSeparator']
  StepperTitle: typeof import("../../app/components/ui/stepper/index")['StepperTitle']
  StepperTrigger: typeof import("../../app/components/ui/stepper/index")['StepperTrigger']
  Switch: typeof import("../../app/components/ui/switch/index")['Switch']
  Textarea: typeof import("../../app/components/ui/textarea/index")['Textarea']
  Toggle: typeof import("../../app/components/ui/toggle/index")['Toggle']
  Tooltip: typeof import("../../app/components/ui/tooltip/index")['Tooltip']
  TooltipContent: typeof import("../../app/components/ui/tooltip/index")['TooltipContent']
  TooltipProvider: typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']
  TooltipTrigger: typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']
  VitePwaManifest: typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
  NuxtPwaManifest: typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
  NuxtPwaAssets: typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
  PwaAppleImage: typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
  PwaAppleSplashScreenImage: typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
  PwaFaviconImage: typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
  PwaMaskableImage: typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
  PwaTransparentImage: typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
  NuxtLinkLocale: typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@vue+compiler-dom@3.5.33_2dd188fc485186898f356a806aeb85c3/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
  SwitchLocalePathLink: typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@vue+compiler-dom@3.5.33_2dd188fc485186898f356a806aeb85c3/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
  NuxtPage: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
  NoScript: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyAccordion: LazyComponent<typeof import("../../app/components/ui/accordion/index")['Accordion']>
  LazyAccordionContent: LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionContent']>
  LazyAccordionItem: LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionItem']>
  LazyAccordionTrigger: LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionTrigger']>
  LazyAlert: LazyComponent<typeof import("../../app/components/ui/alert/index")['Alert']>
  LazyAlertDescription: LazyComponent<typeof import("../../app/components/ui/alert/index")['AlertDescription']>
  LazyAlertTitle: LazyComponent<typeof import("../../app/components/ui/alert/index")['AlertTitle']>
  LazyAlertDialog: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']>
  LazyAlertDialogAction: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']>
  LazyAlertDialogCancel: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']>
  LazyAlertDialogContent: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']>
  LazyAlertDialogDescription: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']>
  LazyAlertDialogFooter: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']>
  LazyAlertDialogHeader: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']>
  LazyAlertDialogTitle: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']>
  LazyAlertDialogTrigger: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']>
  LazyAspectRatio: LazyComponent<typeof import("../../app/components/ui/aspect-ratio/index")['AspectRatio']>
  LazyAutoForm: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoForm']>
  LazyAutoFormField: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormField']>
  LazyAutoFormFieldArray: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldArray']>
  LazyAutoFormFieldBoolean: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldBoolean']>
  LazyAutoFormFieldDate: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldDate']>
  LazyAutoFormFieldEnum: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldEnum']>
  LazyAutoFormFieldFile: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldFile']>
  LazyAutoFormFieldInput: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldInput']>
  LazyAutoFormFieldNumber: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldNumber']>
  LazyAutoFormFieldObject: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldObject']>
  LazyAutoFormLabel: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormLabel']>
  LazyConfig: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['Config']>
  LazyConfigItem: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['ConfigItem']>
  LazyFieldProps: LazyComponent<typeof import("../../app/components/ui/auto-form/index")['FieldProps']>
  LazyAvatar: LazyComponent<typeof import("../../app/components/ui/avatar/index")['Avatar']>
  LazyAvatarFallback: LazyComponent<typeof import("../../app/components/ui/avatar/index")['AvatarFallback']>
  LazyAvatarImage: LazyComponent<typeof import("../../app/components/ui/avatar/index")['AvatarImage']>
  LazyBadge: LazyComponent<typeof import("../../app/components/ui/badge/index")['Badge']>
  LazyButton: LazyComponent<typeof import("../../app/components/ui/button/index")['Button']>
  LazyCalendar: LazyComponent<typeof import("../../app/components/ui/calendar/index")['Calendar']>
  LazyCalendarCell: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarCell']>
  LazyCalendarCellTrigger: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarCellTrigger']>
  LazyCalendarGrid: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGrid']>
  LazyCalendarGridBody: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGridBody']>
  LazyCalendarGridHead: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGridHead']>
  LazyCalendarGridRow: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGridRow']>
  LazyCalendarHeadCell: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarHeadCell']>
  LazyCalendarHeader: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarHeader']>
  LazyCalendarHeading: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarHeading']>
  LazyCalendarNextButton: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarNextButton']>
  LazyCalendarPrevButton: LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarPrevButton']>
  LazyCard: LazyComponent<typeof import("../../app/components/ui/card/index")['Card']>
  LazyCardAction: LazyComponent<typeof import("../../app/components/ui/card/index")['CardAction']>
  LazyCardContent: LazyComponent<typeof import("../../app/components/ui/card/index")['CardContent']>
  LazyCardDescription: LazyComponent<typeof import("../../app/components/ui/card/index")['CardDescription']>
  LazyCardFooter: LazyComponent<typeof import("../../app/components/ui/card/index")['CardFooter']>
  LazyCardHeader: LazyComponent<typeof import("../../app/components/ui/card/index")['CardHeader']>
  LazyCardTitle: LazyComponent<typeof import("../../app/components/ui/card/index")['CardTitle']>
  LazyCheckbox: LazyComponent<typeof import("../../app/components/ui/checkbox/index")['Checkbox']>
  LazyDialog: LazyComponent<typeof import("../../app/components/ui/dialog/index")['Dialog']>
  LazyDialogClose: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogClose']>
  LazyDialogContent: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogContent']>
  LazyDialogDescription: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogDescription']>
  LazyDialogFooter: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogFooter']>
  LazyDialogHeader: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogHeader']>
  LazyDialogOverlay: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogOverlay']>
  LazyDialogScrollContent: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogScrollContent']>
  LazyDialogTitle: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogTitle']>
  LazyDialogTrigger: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogTrigger']>
  LazyDropdownMenu: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']>
  LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
  LazyDropdownMenuContent: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
  LazyDropdownMenuGroup: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
  LazyDropdownMenuItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
  LazyDropdownMenuLabel: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
  LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
  LazyDropdownMenuRadioItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
  LazyDropdownMenuSeparator: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
  LazyDropdownMenuShortcut: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
  LazyDropdownMenuSub: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
  LazyDropdownMenuSubContent: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
  LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
  LazyDropdownMenuTrigger: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
  LazyDropdownMenuPortal: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
  LazyFormControl: LazyComponent<typeof import("../../app/components/ui/form/index")['FormControl']>
  LazyFormDescription: LazyComponent<typeof import("../../app/components/ui/form/index")['FormDescription']>
  LazyFormItem: LazyComponent<typeof import("../../app/components/ui/form/index")['FormItem']>
  LazyFormLabel: LazyComponent<typeof import("../../app/components/ui/form/index")['FormLabel']>
  LazyFormMessage: LazyComponent<typeof import("../../app/components/ui/form/index")['FormMessage']>
  LazyFORMITEMINJECTIONKEY: LazyComponent<typeof import("../../app/components/ui/form/index")['FORM_ITEM_INJECTION_KEY']>
  LazyForm: LazyComponent<typeof import("../../app/components/ui/form/index")['Form']>
  LazyFormField: LazyComponent<typeof import("../../app/components/ui/form/index")['FormField']>
  LazyFormFieldArray: LazyComponent<typeof import("../../app/components/ui/form/index")['FormFieldArray']>
  LazyInput: LazyComponent<typeof import("../../app/components/ui/input/index")['Input']>
  LazyLabel: LazyComponent<typeof import("../../app/components/ui/label/index")['Label']>
  LazyMenubar: LazyComponent<typeof import("../../app/components/ui/menubar/index")['Menubar']>
  LazyMenubarCheckboxItem: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarCheckboxItem']>
  LazyMenubarContent: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarContent']>
  LazyMenubarGroup: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarGroup']>
  LazyMenubarItem: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarItem']>
  LazyMenubarLabel: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarLabel']>
  LazyMenubarMenu: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarMenu']>
  LazyMenubarRadioGroup: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarRadioGroup']>
  LazyMenubarRadioItem: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarRadioItem']>
  LazyMenubarSeparator: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarSeparator']>
  LazyMenubarShortcut: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarShortcut']>
  LazyMenubarSub: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarSub']>
  LazyMenubarSubContent: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarSubContent']>
  LazyMenubarSubTrigger: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarSubTrigger']>
  LazyMenubarTrigger: LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarTrigger']>
  LazyPagination: LazyComponent<typeof import("../../app/components/ui/pagination/index")['Pagination']>
  LazyPaginationContent: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationContent']>
  LazyPaginationEllipsis: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationEllipsis']>
  LazyPaginationFirst: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationFirst']>
  LazyPaginationItem: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationItem']>
  LazyPaginationLast: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationLast']>
  LazyPaginationNext: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationNext']>
  LazyPaginationPrevious: LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationPrevious']>
  LazyPopover: LazyComponent<typeof import("../../app/components/ui/popover/index")['Popover']>
  LazyPopoverAnchor: LazyComponent<typeof import("../../app/components/ui/popover/index")['PopoverAnchor']>
  LazyPopoverContent: LazyComponent<typeof import("../../app/components/ui/popover/index")['PopoverContent']>
  LazyPopoverTrigger: LazyComponent<typeof import("../../app/components/ui/popover/index")['PopoverTrigger']>
  LazyProgress: LazyComponent<typeof import("../../app/components/ui/progress/index")['Progress']>
  LazyRadioGroup: LazyComponent<typeof import("../../app/components/ui/radio-group/index")['RadioGroup']>
  LazyRadioGroupItem: LazyComponent<typeof import("../../app/components/ui/radio-group/index")['RadioGroupItem']>
  LazyRangeCalendar: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendar']>
  LazyRangeCalendarCell: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarCell']>
  LazyRangeCalendarCellTrigger: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarCellTrigger']>
  LazyRangeCalendarGrid: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGrid']>
  LazyRangeCalendarGridBody: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridBody']>
  LazyRangeCalendarGridHead: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridHead']>
  LazyRangeCalendarGridRow: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridRow']>
  LazyRangeCalendarHeadCell: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeadCell']>
  LazyRangeCalendarHeader: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeader']>
  LazyRangeCalendarHeading: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeading']>
  LazyRangeCalendarNextButton: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarNextButton']>
  LazyRangeCalendarPrevButton: LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarPrevButton']>
  LazySelect: LazyComponent<typeof import("../../app/components/ui/select/index")['Select']>
  LazySelectContent: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectContent']>
  LazySelectGroup: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectGroup']>
  LazySelectItem: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItem']>
  LazySelectItemText: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItemText']>
  LazySelectLabel: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectLabel']>
  LazySelectScrollDownButton: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']>
  LazySelectScrollUpButton: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']>
  LazySelectSeparator: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectSeparator']>
  LazySelectTrigger: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectTrigger']>
  LazySelectValue: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectValue']>
  LazySeparator: LazyComponent<typeof import("../../app/components/ui/separator/index")['Separator']>
  LazySlider: LazyComponent<typeof import("../../app/components/ui/slider/index")['Slider']>
  LazyToaster: LazyComponent<typeof import("../../app/components/ui/sonner/index")['Toaster']>
  LazyStepper: LazyComponent<typeof import("../../app/components/ui/stepper/index")['Stepper']>
  LazyStepperDescription: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperDescription']>
  LazyStepperIndicator: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperIndicator']>
  LazyStepperItem: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperItem']>
  LazyStepperSeparator: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperSeparator']>
  LazyStepperTitle: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperTitle']>
  LazyStepperTrigger: LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperTrigger']>
  LazySwitch: LazyComponent<typeof import("../../app/components/ui/switch/index")['Switch']>
  LazyTextarea: LazyComponent<typeof import("../../app/components/ui/textarea/index")['Textarea']>
  LazyToggle: LazyComponent<typeof import("../../app/components/ui/toggle/index")['Toggle']>
  LazyTooltip: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['Tooltip']>
  LazyTooltipContent: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipContent']>
  LazyTooltipProvider: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']>
  LazyTooltipTrigger: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']>
  LazyVitePwaManifest: LazyComponent<typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
  LazyNuxtPwaManifest: LazyComponent<typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
  LazyNuxtPwaAssets: LazyComponent<typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
  LazyPwaAppleImage: LazyComponent<typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']>
  LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']>
  LazyPwaFaviconImage: LazyComponent<typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']>
  LazyPwaMaskableImage: LazyComponent<typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']>
  LazyPwaTransparentImage: LazyComponent<typeof import("../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magicast@0.5.2_vite@7.3.2_@types+node@25.6.0_jiti@2.6.1_lightningc_72ac05ab426285b5df595b960fcd9435/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']>
  LazyNuxtLinkLocale: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@vue+compiler-dom@3.5.33_2dd188fc485186898f356a806aeb85c3/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
  LazySwitchLocalePathLink: LazyComponent<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@vue+compiler-dom@3.5.33_2dd188fc485186898f356a806aeb85c3/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@parcel+watcher@2.5.6_@types+nod_1a72eee85516e2a71aee4cbc22f23041/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
