// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/increase-downloads-count': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/increase-downloads-count.post').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.2_db0@0.3.4_drizzle-orm@0.44.7_@cloudflare+workers-types@4.2026_fb5bb46bfc936afa4e8d7a694e87950e/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/sitemap_index.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@8.0.14_@nuxt+schema@4.4.2_magicast@0.5.2_nuxt@3.21.2_@emnapi+core@1.10._e9431b662729eec254e3fd4a3b26e04a/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap_index.xml').default>>>>
    }
    '/__sitemap__/**:sitemap': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@8.0.14_@nuxt+schema@4.4.2_magicast@0.5.2_nuxt@3.21.2_@emnapi+core@1.10._e9431b662729eec254e3fd4a3b26e04a/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap/[sitemap].xml').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@8.0.14_@nuxt+schema@4.4.2_magicast@0.5.2_nuxt@3.21.2_@emnapi+core@1.10._e9431b662729eec254e3fd4a3b26e04a/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@8.0.14_@nuxt+schema@4.4.2_magicast@0.5.2_nuxt@3.21.2_@emnapi+core@1.10._e9431b662729eec254e3fd4a3b26e04a/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap.xml').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+robots@6.0.8_@nuxt+schema@4.4.2_magicast@0.5.2_nuxt@3.21.2_@emnapi+core@1.10.0__e6a9f6c4b50cedbe6f36a336da7a242d/node_modules/@nuxtjs/robots/dist/runtime/server/routes/robots-txt').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@emnapi+core@1.10.0_@emnapi+runtime@1.10.0_@vue+compiler-dom@3.5.33_2dd188fc485186898f356a806aeb85c3/node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
  }
}
export {}